#!/usr/bin/env bash
# Deterministic tests for the collectors: builds the fixtures, runs detect.sh and probes.sh on
# each, normalises the output and diffs it against tests/expected/; then runs gate.sh on each saved
# issue payload under tests/fixtures/issues/ and diffs its state line the same way. No network, no gh.
#
# How the output is made stable:
# - a shim directory is prepended to PATH with `gh` and `gitleaks` that exit 1, so both collectors
#   take their "unavailable" branch whatever the machine has installed (the gitleaks line is
#   therefore blank: the shim prints nothing);
# - git reads no user or system configuration (GIT_CONFIG_GLOBAL, GIT_CONFIG_NOSYSTEM), so the
#   `git hooks dir` line is always `default` and signing settings never interfere;
# - AIFIER_SINCE is an absolute date, so the activity window of probes.sh does not slide with the
#   calendar (every fixture is below the 20-commit threshold and falls back to the last 100);
# - the `date:` lines are replaced by DATE and the fixture path by ROOT;
# - no line is dropped.
# Usage: bash tests/run.sh        (compare)      UPDATE=1 bash tests/run.sh   (regenerate expected)
set -u
cd "$(git rev-parse --show-toplevel)" || exit 1
command -v jq >/dev/null 2>&1 || { echo "tests: BLOCKED, jq is required by detect.sh"; exit 1; }

work="$(mktemp -d "${TMPDIR:-/tmp}/aifier-tests.XXXXXX")"; work="$(cd "$work" && pwd)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/bin"
printf '#!/bin/sh\nexit 1\n' > "$work/bin/gh"; printf '#!/bin/sh\nexit 1\n' > "$work/bin/gitleaks"
chmod +x "$work/bin/gh" "$work/bin/gitleaks"
export PATH="$work/bin:$PATH" GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 TZ=UTC LC_ALL=C
export AIFIER_SINCE="2026-08-01"

bash tests/fixtures/make.sh "$work/fixtures" >/dev/null || { echo "tests: fixture build failed"; exit 1; }
root="$work/fixtures"

normalise_detect() { sed -E 's/^(# draft generated by aifier init detection on )[0-9-]+;/\1DATE;/'; }
normalise_probes() { sed -e 's/^- root: .*$/- root: ROOT/' -e "s#$root/[A-Za-z0-9_-]*#ROOT#g" -e 's/^- date: .*$/- date: DATE/'; }

fail=0
for fx in two-stacks docs-only dormant with-secret; do
  bash skills/init/detect.sh "$root/$fx" | normalise_detect > "$work/$fx.detect.yml"
  bash skills/assess/probes.sh "$root/$fx" | normalise_probes > "$work/$fx.probes.md"
  for kind in detect.yml probes.md; do
    expected="tests/expected/$fx.$kind"
    if [ "${UPDATE:-}" = 1 ]; then cp "$work/$fx.$kind" "$expected"; continue; fi
    if ! diff -u "$expected" "$work/$fx.$kind"; then echo "tests: $fx $kind differs"; fail=1; fi
  done
done
# the gates runner on a fixture whose gates are shell one-liners: the block is diffed, logs stay in the fixture
normalise_gates() { sed -E -e 's/^Date: [0-9T-]+ ·/Date: DATE ·/' -e "s#(/private)?$root/[A-Za-z0-9_-]*#ROOT#g"; }
gates_case() {  # <name> <args...>: runs the runner, normalises the block, appends the runner's own exit code
  name="$1"; shift
  bash skills/gates/run.sh "$root/gates-runner/aifier.yml" "$@" > "$work/$name.raw"; code=$?
  normalise_gates < "$work/$name.raw" > "$work/$name.txt"; echo "exit: $code" >> "$work/$name.txt"
}
gates_case gates-runner --preflight --compare-ci
gates_case gates-runner-api --area api --family test
for name in gates-runner gates-runner-api; do
  expected="tests/expected/$name.txt"
  if [ "${UPDATE:-}" = 1 ]; then cp "$work/$name.txt" "$expected"; continue; fi
  if ! diff -u "$expected" "$work/$name.txt"; then echo "tests: $name differs"; fail=1; fi
done
# the renderer: the binary renders two configurations into empty trees and two skills in place;
# AIFIER_DATE pins the date; the expected trees were captured identical to the Python renderer's
bin="${AIFIER_BIN:-}"
for c in target/release/aifier target/debug/aifier; do [ -z "$bin" ] && [ -x "$c" ] && bin="$c"; done
[ -n "$bin" ] || { echo "tests: BLOCKED, build the binary first (cargo build --release) or set AIFIER_BIN"; exit 1; }
cp tests/expected/two-stacks.detect.yml "$work/render-two-stacks.yml"   # the draft detect.sh produces, as init confirms it
cp aifier.yml "$work/render-aifier.yml"
for case in two-stacks aifier; do
  out="$work/render/$case"; mkdir -p "$out/skills"
  cp -R skills/build skills/verification-evidence "$out/skills/"
  AIFIER_DATE=DATE "$bin" render "$work/render-$case.yml" templates "$out" --skills "$out/skills" | sed "s#$out/#OUT/#g" > "$out/render.out"
  AIFIER_DATE=DATE "$bin" render "$work/render-$case.yml" templates "$out" | sed "s#$out/#OUT/#g" >> "$out/render.out"
  expected="tests/expected/render/$case"
  if [ "${UPDATE:-}" = 1 ]; then rm -rf "${expected:?}"; mkdir -p tests/expected/render; cp -R "$out" "$expected"; continue; fi
  if ! diff -r "$expected" "$out"; then echo "tests: render $case differs"; fail=1; fi
done
# the installer, offline: from a local checkout into a fixture repository (binary copied from
# target/release), then from a fake release served over file:// (checksum verified), then a
# tampered release (must refuse). The skills archive is never downloaded: AIFIER_SRC points here.
here="$(pwd)"
inst="$root/docs-only"
( cd "$inst" && AIFIER_SRC="$here" sh "$here/install.sh" ) > "$work/install-local.out" 2>&1 || { echo "tests: install from local checkout failed"; cat "$work/install-local.out"; fail=1; }
[ -x "$inst/.aifier/bin/aifier" ] && "$inst/.aifier/bin/aifier" --version | grep -q '^aifier ' || { echo "tests: installer did not copy the binary"; fail=1; }
grep -q '^binary: .aifier/bin/aifier (copied from' "$inst/.aifier/install.yml" || { echo "tests: install.yml lacks the binary line"; fail=1; }
rel="$work/release"; mkdir -p "$rel"
arch="$(uname -m)"; case "$arch" in x86_64|amd64) arch=x86_64;; arm64|aarch64) arch=aarch64;; esac
case "$(uname -s)" in Linux) tgt="$arch-unknown-linux-musl";; Darwin) tgt="$arch-apple-darwin";; *) tgt="unknown";; esac
tar -C "$(dirname "$bin")" -czf "$rel/aifier-v0.0.0-$tgt.tar.gz" aifier
( cd "$rel" && (sha256sum aifier-*.tar.gz 2>/dev/null || shasum -a 256 aifier-*.tar.gz) > SHA256SUMS )
rm -rf "${inst:?}/.aifier/bin"
( cd "$inst" && AIFIER_SRC="$here" AIFIER_REF=v0.0.0 AIFIER_RELEASE_URL="file://$rel" sh "$here/install.sh" ) > "$work/install-release.out" 2>&1 || { echo "tests: install from a release failed"; cat "$work/install-release.out"; fail=1; }
grep -q 'sha256 verified' "$inst/.aifier/install.yml" || { echo "tests: release install did not verify the checksum"; fail=1; }
printf 'tampered' >> "$rel/aifier-v0.0.0-$tgt.tar.gz"
if ( cd "$inst" && AIFIER_SRC="$here" AIFIER_REF=v0.0.0 AIFIER_RELEASE_URL="file://$rel" sh "$here/install.sh" ) > "$work/install-tampered.out" 2>&1; then
  echo "tests: installer accepted a tampered binary"; fail=1
else
  grep -q 'checksum mismatch' "$work/install-tampered.out" || { echo "tests: tampered install failed for another reason"; cat "$work/install-tampered.out"; fail=1; }
fi
# gate.sh decides from the payload alone (--from): the gh shim is never reached
for fx in tests/fixtures/issues/*.json; do
  name="issue-$(basename "$fx" .json)"
  bash skills/gate/gate.sh --from "$fx" --prefix sdlc > "$work/$name.txt"
  expected="tests/expected/$name.txt"
  if [ "${UPDATE:-}" = 1 ]; then cp "$work/$name.txt" "$expected"; continue; fi
  if ! diff -u "$expected" "$work/$name.txt"; then echo "tests: $name differs"; fail=1; fi
done
[ "${UPDATE:-}" = 1 ] && { echo "tests: expected files regenerated"; exit 0; }
[ "$fail" = 0 ] && echo "tests: OK"
exit $fail
