#!/usr/bin/env bash
# Deterministic tests for the collectors: builds the fixtures, runs detect.sh and probes.sh on
# each, normalises the output and diffs it against tests/expected/; then runs gate.sh on each saved
# issue payload under tests/fixtures/issues/ and diffs its state line the same way. No network, no gh.
#
# How the output is made stable:
# - a shim directory is prepended to PATH with `gh` and `gitleaks` that exit 1, so both collectors
#   take their "unavailable" branch whatever the machine has installed (the gitleaks line is
#   therefore blank: the shim prints nothing);
# - git reads no user or system configuration (GIT_CONFIG_GLOBAL, GIT_CONFIG_NOSYSTEM), so the
#   `git hooks dir` line is always `default` and signing settings never interfere;
# - AIFIER_SINCE is an absolute date, so the activity window of probes.sh does not slide with the
#   calendar (every fixture is below the 20-commit threshold and falls back to the last 100);
# - the `date:` lines are replaced by DATE and the fixture path by ROOT;
# - no line is dropped.
# Usage: bash tests/run.sh        (compare)      UPDATE=1 bash tests/run.sh   (regenerate expected)
set -u
cd "$(git rev-parse --show-toplevel)" || exit 1
command -v jq >/dev/null 2>&1 || { echo "tests: BLOCKED, jq is required by detect.sh"; exit 1; }

work="$(mktemp -d "${TMPDIR:-/tmp}/aifier-tests.XXXXXX")"; work="$(cd "$work" && pwd)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/bin"
printf '#!/bin/sh\nexit 1\n' > "$work/bin/gh"; printf '#!/bin/sh\nexit 1\n' > "$work/bin/gitleaks"
chmod +x "$work/bin/gh" "$work/bin/gitleaks"
export PATH="$work/bin:$PATH" GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 TZ=UTC LC_ALL=C
export AIFIER_SINCE="2026-08-01"

bash tests/fixtures/make.sh "$work/fixtures" >/dev/null || { echo "tests: fixture build failed"; exit 1; }
root="$work/fixtures"

normalise_detect() { sed -E 's/^(# draft generated by aifier init detection on )[0-9-]+;/\1DATE;/'; }
normalise_probes() { sed -e 's/^- root: .*$/- root: ROOT/' -e "s#$root/[A-Za-z0-9_-]*#ROOT#g" -e 's/^- date: .*$/- date: DATE/'; }

fail=0
for fx in two-stacks docs-only dormant with-secret; do
  bash skills/init/detect.sh "$root/$fx" | normalise_detect > "$work/$fx.detect.yml"
  bash skills/assess/probes.sh "$root/$fx" | normalise_probes > "$work/$fx.probes.md"
  for kind in detect.yml probes.md; do
    expected="tests/expected/$fx.$kind"
    if [ "${UPDATE:-}" = 1 ]; then cp "$work/$fx.$kind" "$expected"; continue; fi
    if ! diff -u "$expected" "$work/$fx.$kind"; then echo "tests: $fx $kind differs"; fail=1; fi
  done
done
# the gates runner on a fixture whose gates are shell one-liners: the block is diffed, logs stay in the fixture
normalise_gates() { sed -E -e 's/^Date: [0-9T-]+ ·/Date: DATE ·/' -e "s#(/private)?$root/[A-Za-z0-9_-]*#ROOT#g"; }
gates_case() {  # <name> <args...>: runs the runner, normalises the block, appends the runner's own exit code
  name="$1"; shift
  bash skills/gates/run.sh "$root/gates-runner/aifier.yml" "$@" > "$work/$name.raw"; code=$?
  normalise_gates < "$work/$name.raw" > "$work/$name.txt"; echo "exit: $code" >> "$work/$name.txt"
}
gates_case gates-runner --preflight --compare-ci
gates_case gates-runner-api --area api --family test
for name in gates-runner gates-runner-api; do
  expected="tests/expected/$name.txt"
  if [ "${UPDATE:-}" = 1 ]; then cp "$work/$name.txt" "$expected"; continue; fi
  if ! diff -u "$expected" "$work/$name.txt"; then echo "tests: $name differs"; fail=1; fi
done
# gate.sh decides from the payload alone (--from): the gh shim is never reached
for fx in tests/fixtures/issues/*.json; do
  name="issue-$(basename "$fx" .json)"
  bash skills/gate/gate.sh --from "$fx" --prefix sdlc > "$work/$name.txt"
  expected="tests/expected/$name.txt"
  if [ "${UPDATE:-}" = 1 ]; then cp "$work/$name.txt" "$expected"; continue; fi
  if ! diff -u "$expected" "$work/$name.txt"; then echo "tests: $name differs"; fail=1; fi
done
[ "${UPDATE:-}" = 1 ] && { echo "tests: expected files regenerated"; exit 0; }
[ "$fail" = 0 ] && echo "tests: OK"
exit $fail
