#!/usr/bin/env bash
# aifier init detection: deterministic facts about the repository, printed as a draft aifier.yml
# on stdout. No model, no network except `gh` when available. Read-only.
# Exit 1 with `BLOCKED: not a git repository` outside a git work tree.
set -u
cd "${1:-.}" 2>/dev/null || { echo "BLOCKED: cannot cd to ${1:-.}"; exit 1; }
top="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "BLOCKED: not a git repository"; exit 1; }
cd "$top" || exit 1
have() { command -v "$1" >/dev/null 2>&1; }
yq() { printf '%s\n' "$*"; }
remote="$(git remote get-url origin 2>/dev/null || true)"
# repo_of <remote url>: owner/repo for github.com (no subgroups there), the full path after the
# host elsewhere (gitlab subgroups, self-hosted forges); `unknown` for a local path or no remote
repo_of() {
  r="${1%/}"; r="${r%.git}"
  case "$r" in
    file://*|''|/*|./*|../*) echo unknown; return;;
    *://*) host="${r#*://}"; host="${host%%/*}"; host="${host##*@}"; path="${r#*://}"; path="${path#*/}";;
    *@*:*) host="${r#*@}"; host="${host%%:*}"; path="${r#*:}";;
    *) echo unknown; return;;
  esac
  path="${path#/}"
  case "$path" in ''|*/) echo unknown; return;; esac
  case "$host" in
    github.com) printf '%s\n' "$path" | awk -F/ '{ if (NF >= 2) print $(NF-1) "/" $NF; else print "unknown" }';;
    *) printf '%s\n' "$path";;
  esac
}
repo="$(repo_of "$remote")"
proj="${repo##*/}"; [ "$repo" = unknown ] && proj="$(basename "$(pwd)")"
forge="unknown"; case "$remote" in *github.com*) forge=github;; *gitlab*) forge=gitlab;; esac
# default branch: origin/HEAD, then origin/main, origin/master, then the current branch
default="$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
[ -z "$default" ] && git show-ref --verify --quiet refs/remotes/origin/main && default=main
[ -z "$default" ] && git show-ref --verify --quiet refs/remotes/origin/master && default=master
[ -z "$default" ] && default="$(git branch --show-current 2>/dev/null)"
default="${default:-unknown}"
# language: French when at least two README lines carry a French heading or marker word
lang="en"
if [ -f README.md ] && [ "$(grep -ciE '^(## |# )?(utilisation|pr[ée]requis|fonctionnalit|d[ée]marrage|contribuer)' README.md)" -ge 2 ]; then lang="fr"; fi
engines=""; [ -d .claude ] || [ -f CLAUDE.md ] && engines="claude-code"
[ -d .opencode ] && engines="${engines:+$engines, }opencode"; [ -d .pi ] && engines="${engines:+$engines, }pi"
ci_all=""; ci_count=0
for f in .github/workflows/*.y*ml .gitlab-ci.yml cloudbuild*.y*ml; do
  [ -f "$f" ] || continue
  ci_all="$ci_all$f"$'\n'; ci_count=$((ci_count + 1))
done
ci_first="${ci_all%%$'\n'*}"
yq "# draft generated by aifier init detection on $(date +%F); review before confirming"
yq "project: $proj"; yq "forge: $forge"; yq "repo: $repo"; yq "language: $lang"
yq "engines: [${engines:-claude-code}]"
yq "branches:"; yq "  default: $default"; yq "  target: $default"
yq "labels:"; yq "  prefix: \"sdlc\""; yq "  states: [todo, in-progress, done, partial, needs-input]"; yq "  pr_states: [ok, need-work, rejected]"
# areas: directories holding their own manifest, else the root; dependency, example, template and
# fixture trees are not areas. Paths are read NUL-separated so spaces survive.
areas=""
while IFS= read -r -d '' m; do
  case "$m" in
    node_modules/*|*/node_modules/*|vendor/*|*/vendor/*|examples/*|*/examples/*|templates/*|*/templates/*|fixtures/*|*/fixtures/*|.git/*|.*/*|*/.*/*) continue;;
  esac
  case "$m" in
    pyproject.toml|package.json|go.mod|Cargo.toml|pom.xml|build.gradle|build.gradle.kts) d=".";;
    */pyproject.toml|*/package.json|*/go.mod|*/Cargo.toml|*/pom.xml|*/build.gradle|*/build.gradle.kts) d="${m%/*}";;
    *) continue;;
  esac
  areas="$areas$d"$'\n'
done < <(git ls-files -z 2>/dev/null)
areas="$(printf '%s' "$areas" | sort -u)"
# no manifest at all: a documentation or configuration repository is still one area
[ -z "$areas" ] && areas="."
# a root package.json without scripts is tooling residue, not an area, when sub-areas exist
has_scripts() { if have jq; then [ "$(jq '.scripts // {} | length' "$1")" != "0" ]; else grep -q '"scripts"' "$1"; fi; }
if [ "$(printf '%s\n' "$areas" | wc -l)" -gt 1 ] && [ -f package.json ] && ! has_scripts package.json; then
  areas="$(printf '%s\n' "$areas" | grep -vx '.')"
fi
# kind_of <dir/ or empty>: prints "<kind>|<other manifests>"; the first manifest found decides
# the kind, the others are only reported, no field is overwritten by a second manifest
kind_of() {
  k=""; a=""
  for m in pyproject.toml package.json go.mod Cargo.toml pom.xml build.gradle build.gradle.kts; do
    [ -f "$1$m" ] || continue
    case "$m" in pyproject.toml) mk=python;; package.json) mk=node;; go.mod) mk=go;; Cargo.toml) mk=rust;; *) mk=jvm;; esac
    if [ -z "$k" ]; then k="$mk"; elif [ "$mk" != "$k" ]; then a="${a:+$a, }$m"; fi
  done
  printf '%s|%s\n' "${k:-docs}" "$a"
}
yq "areas:"
while IFS= read -r d; do
  [ -n "$d" ] || continue
  dd="$d/"; [ "$d" = "." ] && dd=""
  IFS='|' read -r kind also <<< "$(kind_of "$dd")"
  stack="$kind"
  case "$kind" in
    python) grep -qi fastapi "${dd}pyproject.toml" && stack="python-fastapi"; grep -qi django "${dd}pyproject.toml" && stack="python-django";;
    node) grep -q '"next"' "${dd}package.json" && stack="nextjs-react" || { grep -q '"react"' "${dd}package.json" && stack="react"; };;
  esac
  key="$d"; [ "$d" = "." ] && key="root"
  yq "  $key: { guide: ${dd}AGENTS.md, stack: $stack }${also:+  # also found: $also}"
done <<EOF
$areas
EOF
yq "gates:"
while IFS= read -r d; do
  [ -n "$d" ] || continue
  dd="$d/"; [ "$d" = "." ] && dd=""; key="$d"; [ "$d" = "." ] && key="root"
  IFS='|' read -r kind also <<< "$(kind_of "$dd")"
  lint=""; type=""; test=""; build=""
  case "$kind" in
    python)
      grep -qE '\[tool\.ruff' "${dd}pyproject.toml" && lint="ruff check . && ruff format --check ."
      [ -z "$lint" ] && { [ -f "${dd}.flake8" ] || grep -q flake8 "${dd}pyproject.toml"; } && lint="flake8 ."
      { grep -qE '\[tool\.mypy' "${dd}pyproject.toml" || [ -f "${dd}mypy.ini" ]; } && type="mypy ."
      grep -qE '\[tool\.pyright' "${dd}pyproject.toml" && type="pyright"
      test="pytest";;
    node)
      if have jq; then s="$(jq -r '.scripts // {} | keys | join(" ")' "${dd}package.json")"
      else s="$(sed -n '/"scripts"/,/}/p' "${dd}package.json" | grep -oE '^[[:space:]]*"[^"]+"' | tr -d ' "' | tr '\n' ' ')"; fi
      for k in lint; do echo "$s" | grep -qw "$k" && lint="npm run $k"; done
      for k in typecheck type-check tsc; do echo "$s" | grep -qw "$k" && type="npm run $k"; done
      [ -z "$type" ] && [ -f "${dd}tsconfig.json" ] && type="npx tsc --noEmit"
      for k in test test:ci; do echo "$s" | grep -qw "$k" && test="npm run $k"; done
      echo "$s" | grep -qw build && build="npm run build";;
    go) lint="go vet ./..."; test="go test ./..."; build="go build ./...";;
    rust) lint="cargo clippy -- -D warnings"; test="cargo test"; build="cargo build";;
  esac
  yq "  $key:"
  val() { [ -n "$1" ] && printf '"%s"' "$1" || printf 'null'; }
  yq "    lint: $(val "$lint")"
  yq "    typecheck: $(val "$type")"
  yq "    test: $(val "$test")"
  yq "    build: $(val "$build")"
done <<EOF
$areas
EOF
yq "ci:"
if [ -z "$ci_first" ]; then yq "  file: null"
else
  yq "  file: $ci_first"
  [ "$ci_count" -gt 1 ] && { yq "  files:"; printf '%s' "$ci_all" | sed 's/^/    - /'; }
fi
yq "  required_checks: []"
yq "guards: []"
yq "protected_paths: []"
yq "memory:"; yq "  rules: docs/learned-rules.md"; yq "  decisions: docs/decisions"; yq "  handoff: docs/handoff.md"
yq "existing:"
for f in AGENTS.md CLAUDE.md .github/PULL_REQUEST_TEMPLATE.md .github/ISSUE_TEMPLATE docs/adr docs/decisions docs/learned-rules.md docs/handoff.md CHANGELOG.md CONTRIBUTING.md .claude/skills .agents/skills .aifier; do [ -e "$f" ] && yq "  - $f"; done
exit 0
