#!/usr/bin/env bash
# aifier init detection: deterministic facts about the repository, printed as a draft aifier.yml
# on stdout. No model, no network except `gh` when available. Read-only.
set -u
cd "${1:-.}" && cd "$(git rev-parse --show-toplevel)" || exit 1
have() { command -v "$1" >/dev/null 2>&1; }
yq() { printf '%s\n' "$*"; }
remote="$(git remote get-url origin 2>/dev/null || true)"
repo="$(printf '%s' "$remote" | sed -E 's#\.git$##; s#.*[:/]([^/]+/[^/]+)$#\1#')"
proj="${repo##*/}"; [ -z "$proj" ] && proj="$(basename "$(pwd)")"
forge="unknown"; case "$remote" in *github.com*) forge=github;; *gitlab*) forge=gitlab;; esac
default="$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#origin/##')"; default="${default:-$(git branch --show-current)}"
lang="en"; [ -f README.md ] && grep -qiE '^(## |# )?(installation|utilisation|pr[ée]requis|fonctionnalit)' README.md && lang="fr"
engines=""; [ -d .claude ] || [ -f CLAUDE.md ] && engines="claude-code"
[ -d .opencode ] && engines="${engines:+$engines, }opencode"; [ -d .pi ] && engines="${engines:+$engines, }pi"
ci=""; for f in .github/workflows/*.y*ml .gitlab-ci.yml cloudbuild*.y*ml; do [ -f "$f" ] && ci="${ci:+$ci, }$f"; done
yq "# draft generated by aifier init detection on $(date +%F); review before confirming"
yq "project: $proj"; yq "forge: $forge"; yq "repo: $repo"; yq "language: $lang"
yq "engines: [${engines:-claude-code}]"
yq "branches:"; yq "  default: $default"; yq "  target: $default"
yq "labels:"; yq "  prefix: \"sdlc\""; yq "  states: [todo, in-progress, done, partial, needs-input]"; yq "  pr_states: [ok, need-work, rejected]"
# areas: directories holding their own manifest, else the root
areas=""
for m in $(git ls-files | grep -E '(^|/)(pyproject\.toml|package\.json|go\.mod|Cargo\.toml|pom\.xml|build\.gradle(\.kts)?)$' | grep -vE 'node_modules|/\.' ); do
  d="$(dirname "$m")"; areas="$areas $d"
done
areas="$(printf '%s\n' $areas | sort -u)"
# no manifest at all: a documentation or configuration repository is still one area
[ -z "$areas" ] && areas="."
# a root package.json without scripts is tooling residue, not an area, when sub-areas exist
if [ "$(printf '%s\n' $areas | wc -l)" -gt 1 ] && [ -f package.json ] && have jq && [ "$(jq '.scripts // {} | length' package.json)" = "0" ]; then
  areas="$(printf '%s\n' $areas | grep -vx '.')"
fi
yq "areas:"
for d in $areas; do
  stack="docs"; dd="$d/"; [ "$d" = "." ] && dd=""
  if [ -f "${dd}pyproject.toml" ]; then stack="python"; grep -qi fastapi "${dd}pyproject.toml" && stack="python-fastapi"; grep -qi django "${dd}pyproject.toml" && stack="python-django"; fi
  if [ -f "${dd}package.json" ]; then stack="node"; grep -q '"next"' "${dd}package.json" && stack="nextjs-react" || { grep -q '"react"' "${dd}package.json" && stack="react"; }; fi
  [ -f "${dd}go.mod" ] && stack="go"; [ -f "${dd}Cargo.toml" ] && stack="rust"; { [ -f "${dd}pom.xml" ] || ls "${dd}"build.gradle* >/dev/null 2>&1; } && stack="jvm"
  key="$d"; [ "$d" = "." ] && key="root"
  yq "  $key: { guide: ${dd}AGENTS.md, stack: $stack }"
done
yq "gates:"
for d in $areas; do
  dd="$d/"; [ "$d" = "." ] && dd=""; key="$d"; [ "$d" = "." ] && key="root"
  lint=""; type=""; test=""; build=""
  if [ -f "${dd}pyproject.toml" ]; then
    grep -qE '\[tool\.ruff' "${dd}pyproject.toml" && lint="ruff check . && ruff format --check ."
    [ -z "$lint" ] && { [ -f "${dd}.flake8" ] || grep -q flake8 "${dd}pyproject.toml"; } && lint="flake8 ."
    { grep -qE '\[tool\.mypy' "${dd}pyproject.toml" || [ -f "${dd}mypy.ini" ]; } && type="mypy ."
    grep -qE '\[tool\.pyright' "${dd}pyproject.toml" && type="pyright"
    test="pytest"
  fi
  if [ -f "${dd}package.json" ] && have jq; then
    s="$(jq -r '.scripts // {} | keys | join(" ")' "${dd}package.json")"
    for k in lint; do echo "$s" | grep -qw "$k" && lint="npm run $k"; done
    for k in typecheck type-check tsc; do echo "$s" | grep -qw "$k" && type="npm run $k"; done
    [ -z "$type" ] && [ -f "${dd}tsconfig.json" ] && type="npx tsc --noEmit"
    for k in test test:ci; do echo "$s" | grep -qw "$k" && test="npm run $k"; done
    echo "$s" | grep -qw build && build="npm run build"
  fi
  [ -f "${dd}go.mod" ] && { lint="go vet ./..."; test="go test ./..."; build="go build ./..."; }
  [ -f "${dd}Cargo.toml" ] && { lint="cargo clippy -- -D warnings"; test="cargo test"; build="cargo build"; }
  yq "  $key:"
  val() { [ -n "$1" ] && printf '"%s"' "$1" || printf 'null'; }
  yq "    lint: $(val "$lint")"
  yq "    typecheck: $(val "$type")"
  yq "    test: $(val "$test")"
  yq "    build: $(val "$build")"
done
yq "ci:"; yq "  file: ${ci:-null}"; yq "  required_checks: []"
yq "guards: []"
yq "protected_paths: []"
yq "memory:"; yq "  rules: docs/learned-rules.md"; yq "  decisions: docs/decisions"; yq "  handoff: docs/handoff.md"
yq "existing:"
for f in AGENTS.md CLAUDE.md .github/PULL_REQUEST_TEMPLATE.md .github/ISSUE_TEMPLATE docs/adr docs/decisions docs/learned-rules.md docs/handoff.md CHANGELOG.md CONTRIBUTING.md .claude/skills .agents/skills .aifier; do [ -e "$f" ] && yq "  - $f"; done
exit 0
